# Generated by Django 3.2.4 on 2023-06-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=200)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Negada', 'Negada')], max_length=10, null=True)),
            ],
        ),
    ]
